name: Create release from tag

on:
  push:
    tags:
      - '*'

jobs:
  gradle:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            build_commands: ./gradlew -i jpackage
            files: |
              build/jpackage/*.deb
              build/jpackage/*.rpm
#          - os: windows-latest
#            build_commands: .\gradlew.bat jpackage
#            files: build/jpackage/*.msi

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        run: |
          wget -q -O - https://download.bell-sw.com/pki/GPG-KEY-bellsoft | sudo apt-key add -
          echo "deb https://apt.bell-sw.com/ stable main" | sudo tee /etc/apt/sources.list.d/bellsoft.list
          sudo apt-get update
          sudo apt-get install -y bellsoft-java17-full

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Execute Gradle build
        run: ${{ matrix.build_commands }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.files }}
