name: gradle jlinkZip

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: write

jobs:
  gradle:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            build_commands: sh ci/x86_64-ubuntu-22.04-release.sh
            files: |
              build/distributions/*.zip

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Gradle build
        run: ${{ matrix.build_commands }}

      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          path: ${{ matrix.files }}
          if-no-files-found: error
